apiVersion: v1
kind: Secret
metadata:
  name: telegraf-secrets
type: Opaque
stringData:
  INFLUXDB_DB: local_monitoring
  INFLUXDB_URL: http://influx:8086
  INFLUXDB_USER: root
  INFLUXDB_USER_PASSWORD: root1234
---
apiVersion: v1
kind: Secret
metadata:
  name: influx-creds
type: Opaque
stringData:
  INFLUXDB_DB: local_monitoring
  INFLUXDB_URL: http://influx:8086
  INFLUXDB_USER: root
  INFLUXDB_USER_PASSWORD: root1234