apiVersion: apps/v1
kind: Deployment
metadata:
  name: client
  labels:
    app: client
spec:
  replicas: 2
  selector:
    matchLabels:
      app: client
  template:
    metadata:
      labels:
        app: client
    spec:
      containers:
      - name: client
        image: mckp/helper-client
        env:
          - name: SPACE_KEY
            value: foobar
          - name: SPACE_SECRET
            value: bazborp
        ports:
        - containerPort: 5000