apiVersion: apps/v1
kind: Deployment
metadata:
  name: client
  labels:
    app: client
spec:
  replicas: 2
  selector:
    matchLabels:
      app: client
  template:
    metadata:
      labels:
        app: client
    spec:
      containers:
      - name: client
        image: mckp/helper-client
        env:
          - name: SPACE_KEY
            valueFrom:
              secretKeyRef:
                name: client-secrets
                key: SPACE_KEY
          - name: SPACE_SECRET
            valueFrom:
              secretKeyRef:
                name: client-secrets
                key: SPACE_SECRET
          - name: JWT_SECRET
            valueFrom:
              secretKeyRef:
                name: client-secrets
                key: JWT_SECRET
        ports:
        - containerPort: 5000