apiVersion: apps/v1
kind: Deployment
metadata:
  name: client
  labels:
    app: client
spec:
  replicas: 2
  selector:
    matchLabels:
      app: client
  template:
    metadata:
      labels:
        app: client
    spec:
      containers:
        # It is important that our application
        # code is the _first_ container defined
        # due to patches. Maybe one day we can
        # fix this but for now, IF YOU COPY THIS
        # YOU MUST KEEP YOUR CUSTOM DOCKER IMAGE
        # AS THE FIRST CONTAINER OR ELSE
      - name: client
        image: mckp/helper-client
        livenessProbe:
            httpGet:
              path: /__internal__/healthcheck
              port: 5000
            initialDelaySeconds: 3
            periodSeconds: 3
        readinessProbe:
          httpGet:
            path: /__internal__/healthcheck
            port: 5000
          initialDelaySeconds: 3
          periodSeconds: 3   
        env:
          - name: SPACE_KEY
            valueFrom:
              secretKeyRef:
                name: client-secrets
                key: SPACE_KEY
          - name: SPACE_SECRET
            valueFrom:
              secretKeyRef:
                name: client-secrets
                key: SPACE_SECRET
          - name: JWT_SECRET
            valueFrom:
              secretKeyRef:
                name: client-secrets
                key: JWT_SECRET
          - name: UPSTREAM_API_URL_BASE
            value: http://$(API_SERVICE_HOST):$(API_SERVICE_PORT)
        ports:
        - containerPort: 5000